apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  namespace: $NS
spec:
  hostPath:
    path: ${V_RUNTIME_CONTENTS_DIR}
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: $NS
spec:
  volumeName: nginx-pv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: $NS
  labels:
    run: nginx-service
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: ${NGINX_NODEPORT}
      protocol: TCP
  selector:
    run: nginx

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: $NS
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx
        app: nginx
    spec:
      containers:
        - name: frontend
          image: nginx:1.14.2
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: static-content-vol
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: static-content-vol
          persistentVolumeClaim:
            claimName: nginx-pvc
