apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-entrypoint-pv
  namespace: postgres
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: ${ENTRY_POINT_DB_LOC}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-entrypoint-pvc
  namespace: postgres
  labels:
    app: postgres
spec:
  volumeName: postgres-entrypoint-pv
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi