apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres
data:
  POSTGRES_DB: "mydb"
  POSTGRES_USER: "sachin"
  POSTGRES_PASSWORD: "123456"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: postgres
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/postgres"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: postgres
  labels:
    app: postgres
spec:
  volumeName: postgres-pv
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          args:
            - "postgres"
            - "-c"
            - "config_file=/tmp/postgresql.conf"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
            - mountPath: /docker-entrypoint-initdb.d
              name: postgre-entrypoint-db
            - mountPath: /tmp/postgresql.conf
              name: postgresql-conf
              subPath: postgresql.conf
              readOnly: false
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: postgre-entrypoint-db
          persistentVolumeClaim:
            claimName: postgres-entrypoint-pvc
        - name: postgresql-conf
          configMap:
            name: postgresql-conf
            items:
              - key: postgresql.conf
                path: postgresql.conf


---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - name: node-port
      port: 5432
      targetPort: 5432
      nodePort: ${POSTGRES_NODEPORT}
  selector:
    app: postgres