apiVersion: v1
kind: Service
metadata:
  name: redis-primary-svc
  labels:
    app: redis
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      name: redis
      nodePort: ${REDIS_PRIMARY_NODEPORT}
  selector:
    name: redis-primary

---

apiVersion: v1
kind: Service
metadata:
  name: redis-replica-svc
  labels:
    app: redis
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      name: redis
      nodePort: ${REDIS_REPLICA_NODEPORT}
  selector:
    name: redis-replica

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-primary-deployment
  labels:
    name: redis-primary
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-primary
  template:
    metadata:
      labels:
        name: redis-primary
        app: redis
    spec:
      subdomain: primary
      containers:
        - name: redis
          image: redis:3.2.0-alpine
          command:
            - "redis-server"
          args:
            - "--protected-mode"
            - "no"
          ports:
            - containerPort: 6379

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-replica-deployment
  labels:
    name: redis-replica
    app: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      name: redis-replica
  template:
    metadata:
      labels:
        name: redis-replica
        app: redis
    spec:
      subdomain: replica
      containers:
        - name: redis
          image: redis:3.2.0-alpine
          command:
            - "redis-server"
          args:
            - "--slaveof"
            - "redis-primary-svc"
            - "6379"
            - "--protected-mode"
            - "no"
          ports:
            - containerPort: 6379